// Auto-generated by LibreLane
module dac(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk_ref,
  input clk_fb,
  input rst_ni,
  output dac_out,
  input vctrl_in,
  input vctrl_b_in,
  output vctrl_out,
  output vctrl_b_out
);
endmodule
