// Auto-generated by LibreLane
module ook_digital_system(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input q3,
  input q2,
  input q1,
  input q0,
  output rst,
  output clk_ref,
  output vctrl,
  output vctrl_n,
  input data_in_tx,
  output q3_d,
  output q2_d,
  output q1_d,
  output q0_d,
  input rst_n_in,
  input clk,
  output in_tieoff,
  output in_tieon
);
endmodule
