`default_nettype none

module clk_div_async #(
    parameter int unsigned N = 2   // must be a power of 2
) (
    input  wire clk_in,
    input  wire rst_ni,
    output wire [$clog2(N)-1:0] stage_q_out
);

    // Asynchronous ripple divider: a chain of toggle flip-flops (each
    // stage's D tied to its own QN, i.e. Q <= ~Q), with each stage's Q
    // clocking the next. Every stage only has to close timing at its own
    // rate -- stage 0 sees the full clk_in frequency but is nothing more
    // than a single toggle, not an N-bit increment/compare running at that
    // speed. Stage i+1 always runs at half of stage i.
    //
    // Every intermediate stage is exposed (not just the final one) so the
    // top level can pick off any power-of-2 divide ratio up to N as a
    // "tap" -- the gear-shifting detector below selects among these at
    // runtime instead of needing a separate divider per ratio.
    localparam int unsigned STAGES = $clog2(N);

    wire [STAGES-1:0] stage_q;

    reg stage_q0;
    always @(posedge clk_in or negedge rst_ni) begin
        if (!rst_ni) stage_q0 <= 1'b0;
        else         stage_q0 <= ~stage_q0;
    end
    assign stage_q[0] = stage_q0;

    genvar i;
    generate
        for (i = 1; i < STAGES; i = i + 1) begin : g_stage
            reg q;
            always @(posedge stage_q[i-1] or negedge rst_ni) begin
                if (!rst_ni) q <= 1'b0;
                else         q <= ~q;
            end
            assign stage_q[i] = q;
        end
    endgenerate

    assign stage_q_out = stage_q;

endmodule

module dac (
    input  wire clk_ref,   // 80MHz baseband reference
    input  wire clk_fb,    // VCO feedback, target 433.92MHz (100-800MHz range)
    input  wire rst_ni,
    output wire dac_out,

    // Feedthrough to the analog IP: driven from elsewhere on the digital
    // side, not generated by this macro's own logic. Buffered rather than
    // wired straight through so the analog block taps a locally-driven
    // signal at this macro's boundary instead of the original driver
    // having to reach all the way across the floorplan.
    input  wire vctrl_in,
    input  wire vctrl_b_in,
    output wire vctrl_out,
    output wire vctrl_b_out
);

    assign vctrl_out   = vctrl_in;
    assign vctrl_b_out = vctrl_b_in;

    // ------------------------------------------------------------------
    // Reciprocal (period) counter + streak-accelerated bang-bang
    // correction, now with gear-shifting across 7 divider taps
    // (FB_DIV = 128, 256, 512, 1024, 2048, 4096, 8192 -- stage_q[6..12]
    // of the shared 13-stage ripple divider). Starts coarse (128) for
    // fast wide-range acquisition, shifts to finer taps as it converges,
    // and can shift back down if it drifts out of a fine tap's range --
    // gearing up only (no down-shift) would be unsafe, since a fine tap's
    // dead-band is too narrow to ever re-acquire a large excursion in
    // reasonable time.
    //
    // Per tap, two bracket pairs instead of one:
    //   - HOLD_LOW/HOLD_HIGH: same role as the old fixed-tap design --
    //     the tight zone bracketing that tap's target period
    //     (CLK_REF_FREQ*FB_DIV/F_TARGET). Landing here means "on target
    //     for this tap's resolution" -- holds duty, and tries gearing UP
    //     to the next finer tap (single-shot, no debounce).
    //   - BREAK_LOW/BREAK_HIGH: a wider bracket, offset from HOLD by a
    //     fixed +/-GEAR_MARGIN clk_ref cycles. Falling outside this means
    //     the error is too large for this tap's resolution to be the
    //     right tool -- "breaks the gear", shifts DOWN to a coarser tap
    //     (single-shot). Using a fixed cycle offset (not a fixed
    //     frequency offset) is deliberate: the same GEAR_MARGIN cycles
    //     spans a huge frequency range at a coarse tap (wide tolerance,
    //     as befits wide-range acquisition) and a tiny one at a fine tap
    //     (narrow tolerance, so it hands back to a faster-reacting tap
    //     quickly) -- exactly the behavior wanted, for free.
    //
    // A wrong gear-up (landing in HOLD by coincidence, not real
    // convergence) is self-correcting: the very next period at the finer
    // tap will most likely fall outside ITS break band and gear back
    // down on its own -- no separate hysteresis/debounce counters needed,
    // the break check itself is the safety net.
    //
    // At the coarsest tap (128), "outside break" can't gear down further
    // (nowhere lower to go) -- this_is_fast/this_is_slow are NOT gated by
    // break status alone, only by whether a gear change is actually
    // happening, so plain bang-bang correction still runs across the
    // full range at that tap instead of going unresponsive at the edges.
    //
    // Any gear change (up or down) resets per_cnt/streak/last_dir and
    // enters one cycle of "settling": the first fb_edge after a switch is
    // discarded (only used to resync per_cnt), not evaluated, because the
    // 2-FF synchronizer still has up to ~2 cycles of the OLD tap's toggle
    // history draining through its pipeline -- trusting that first edge's
    // measurement would read a garbage mix of old/new tap timing.
    // ------------------------------------------------------------------
    localparam int unsigned MAX_FB_DIV = 8192;
    localparam int unsigned STAGES     = $clog2(MAX_FB_DIV);  // 13
    localparam int unsigned TAP_BITS   = 4;                   // covers stage indices 0..12
    localparam int unsigned TAP_MIN    = 6;                   // stage_q[6]  -> FB_DIV=128  (coarsest/start)
    localparam int unsigned TAP_MAX    = STAGES - 1;          // stage_q[12] -> FB_DIV=8192 (finest)
    localparam int unsigned GEAR_MARGIN = 8;  // clk_ref cycles beyond HOLD before a tap "breaks"

    localparam int unsigned DUTY_BITS    = 13;
    localparam int unsigned PER_CNT_BITS = 13;  // covers up to 8191 clk_ref cycles (worst case ~6554 at 100MHz VCO, FB_DIV=8192)
    localparam int unsigned STREAK_BITS  = 6;   // caps how large one period's bump can grow to
    localparam int unsigned STEP_SHIFT   = 3;   // every tap but TAP_MAX steps 2**STEP_SHIFT duty LSBs per correction, so the extra duty resolution only sharpens TAP_MAX and doesn't slow down acquisition at the coarser taps

    localparam [DUTY_BITS-1:0] DUTY_MAX  = (1 << DUTY_BITS) - 1;
    localparam [DUTY_BITS-1:0] DUTY_INIT = 1 << (DUTY_BITS - 1);
    localparam [STREAK_BITS-1:0] STREAK_MAX = (1 << STREAK_BITS) - 1;

    localparam [1:0] DIR_HOLD = 2'd0;
    localparam [1:0] DIR_DOWN = 2'd1;  // too fast
    localparam [1:0] DIR_UP   = 2'd2;  // too slow

    // Per-tap thresholds as plain case-statement lookups (constants
    // precomputed offline from CLK_REF_FREQ*FB_DIV/F_TARGET), not a
    // runtime-computed array -- keeps every reload a pure selection, zero
    // arithmetic, and avoids relying on SystemVerilog aggregate-literal
    // array init that the synth toolchain's Verilog frontend may not
    // support.
    //   tap : FB_DIV : target period : HOLD          : BREAK (+/-GEAR_MARGIN)
    //     6 :    128 :     23.60     : [  23,   25) : [  15,   33)
    //     7 :    256 :     47.20     : [  47,   49) : [  39,   57)
    //     8 :    512 :     94.40     : [  94,   96) : [  86,  104)
    //     9 :   1024 :    188.79     : [ 188,  190) : [ 180,  198)
    //    10 :   2048 :    377.58     : [ 377,  379) : [ 369,  387)
    //    11 :   4096 :    755.17     : [ 755,  757) : [ 747,  765)
    //    12 :   8192 :   1510.34     : [1509, 1513) : [1472, 1544)
    // tap 12's BREAK is widened to cover ~425-445MHz (not +/-GEAR_MARGIN)
    // so it tolerates measured tail ripple without gearing down; recovery
    // within that range relies on streak escalation, not a coarser tap.
    // tap 12's HOLD is widened to 4 counts (rest stay at 2): at the
    // measured Kvco, a single finest-tap duty LSB moves the VCO further
    // than a 2-count HOLD is wide, so it could never land back inside its
    // own lock window and would perpetually overshoot in and out of it.
    function automatic [PER_CNT_BITS-1:0] tap_hold_low(input [TAP_BITS-1:0] tap);
        case (tap)
            6:       tap_hold_low = 23;
            7:       tap_hold_low = 47;
            8:       tap_hold_low = 94;
            9:       tap_hold_low = 188;
            10:      tap_hold_low = 377;
            11:      tap_hold_low = 755;
            default: tap_hold_low = 1509;  // 12
        endcase
    endfunction

    function automatic [PER_CNT_BITS-1:0] tap_hold_high(input [TAP_BITS-1:0] tap);
        case (tap)
            6:       tap_hold_high = 25;
            7:       tap_hold_high = 49;
            8:       tap_hold_high = 96;
            9:       tap_hold_high = 190;
            10:      tap_hold_high = 379;
            11:      tap_hold_high = 757;
            default: tap_hold_high = 1513;  // 12
        endcase
    endfunction

    // BREAK is HOLD +/-GEAR_MARGIN for every tap except 12 (see table
    // above), so break_low/high are derived from hold_low/high below
    // instead of their own lookup tables, with tap 12 as the one override.

    // Shared 13-stage ripple divider; every stage exposed, tap_sel picks
    // which one currently feeds the synchronizer.
    wire [STAGES-1:0] fb_stage_q;

    clk_div_async #(.N(MAX_FB_DIV)) u_fb_div (
        .clk_in     (clk_fb),
        .rst_ni     (rst_ni),
        .stage_q_out(fb_stage_q)
    );

    reg [TAP_BITS-1:0] tap_sel;

    wire clk_fb_tap = fb_stage_q[tap_sel];

    // 2-FF synchronizer + rising-edge detect: brings clk_fb_tap pulses
    // into the clk_ref domain without ever using clk_fb_tap as a clock.
    reg [2:0] fb_sync;

    always @(posedge clk_ref or negedge rst_ni) begin
        if (!rst_ni) fb_sync <= 3'b0;
        else         fb_sync <= {fb_sync[1:0], clk_fb_tap};
    end

    wire fb_edge = fb_sync[1] & ~fb_sync[2];

    reg [PER_CNT_BITS-1:0] per_cnt;
    reg [DUTY_BITS-1:0]    duty;
    reg [STREAK_BITS-1:0]  streak;
    reg [1:0]              last_dir;
    reg                    settling;

    // hold_low/high/break_low/high always equal tap_hold_low(tap_sel) etc
    // -- they were previously registered and reloaded on every gear
    // change, but that reload always produced exactly this value, so the
    // registers were pure duplication. Combinational instead: same
    // comparators see the same (old, pre-update) tap's thresholds during
    // the edge that changes tap_sel, since tap_sel itself hasn't updated
    // yet at that point -- functionally identical, 52 fewer flops.
    wire [PER_CNT_BITS-1:0] hold_low   = tap_hold_low(tap_sel);
    wire [PER_CNT_BITS-1:0] hold_high  = tap_hold_high(tap_sel);
    wire [PER_CNT_BITS-1:0] break_low  = (tap_sel == TAP_MAX) ? 13'd1472 : (hold_low - GEAR_MARGIN);
    wire [PER_CNT_BITS-1:0] break_high = (tap_sel == TAP_MAX) ? 13'd1544 : (hold_high + GEAR_MARGIN);

    wire [TAP_BITS-1:0] tap_up   = (tap_sel == TAP_MAX) ? tap_sel : tap_sel + 1'b1;
    wire [TAP_BITS-1:0] tap_down = (tap_sel == TAP_MIN) ? tap_sel : tap_sel - 1'b1;

    wire in_break_zone = (per_cnt < break_low) || (per_cnt >= break_high);
    wire in_hold_zone  = (per_cnt >= hold_low) && (per_cnt < hold_high);

    wire gear_down_now = fb_edge && in_break_zone && (tap_sel != TAP_MIN);
    wire gear_up_now   = fb_edge && in_hold_zone  && (tap_sel != TAP_MAX);
    wire gear_change   = gear_down_now || gear_up_now;

    // Bang-bang applies whenever this period isn't causing a gear change
    // and isn't a hold -- this deliberately covers the coarsest-tap edge
    // case where in_break_zone is true but gear_down_now is false (no
    // lower tap to go to): correction still has to run there, not go
    // silent just because the break band was exceeded.
    wire this_is_fast = fb_edge && !gear_change && !in_hold_zone && (per_cnt < hold_low);
    wire this_is_slow = fb_edge && !gear_change && !in_hold_zone && (per_cnt >= hold_high);
    wire [1:0] this_dir = this_is_fast ? DIR_DOWN : this_is_slow ? DIR_UP : DIR_HOLD;
    wire same_streak    = fb_edge && !gear_change && (this_dir == last_dir) && (this_dir != DIR_HOLD);

    wire [DUTY_BITS-1:0] step_unit = (tap_sel == TAP_MAX)
        ? {{(DUTY_BITS-1){1'b0}}, 1'b1}
        : ({{(DUTY_BITS-1){1'b0}}, 1'b1} << STEP_SHIFT);
    // TAP_MAX never escalates -- same fixed 1-LSB step every violating
    // edge regardless of streak, in either direction. streak still counts
    // in the background at TAP_MAX (shared logic with every other tap),
    // it's just unused for sizing the step there.
    wire [DUTY_BITS-1:0] step_amt = (tap_sel == TAP_MAX)
        ? {{(DUTY_BITS-1){1'b0}}, 1'b1}
        : ({{(DUTY_BITS-STREAK_BITS){1'b0}}, streak} << STEP_SHIFT);

    always @(posedge clk_ref or negedge rst_ni) begin
        if (!rst_ni) begin
            tap_sel    <= TAP_MIN[TAP_BITS-1:0];
            per_cnt    <= '0;
            duty       <= DUTY_INIT;
            streak     <= {{(STREAK_BITS-1){1'b0}}, 1'b1};
            last_dir   <= DIR_HOLD;
            settling   <= 1'b0;
        end else if (settling) begin
            // Discard this edge's measurement -- may straddle the old and
            // new tap while the synchronizer drains -- just resync per_cnt
            // and resume normal operation from the next edge on.
            per_cnt <= fb_edge ? '0 : (per_cnt + 1'b1);
            if (fb_edge) settling <= 1'b0;
        end else begin
            per_cnt <= fb_edge ? '0 : (per_cnt + 1'b1);

            if (gear_change) begin
                tap_sel    <= gear_down_now ? tap_down : tap_up;
                streak     <= {{(STREAK_BITS-1){1'b0}}, 1'b1};
                last_dir   <= DIR_HOLD;
                settling   <= 1'b1;
                // duty deliberately untouched here -- a gear change only
                // changes measurement resolution, it doesn't correct
                // anything by itself.
            end else if (fb_edge) begin
                last_dir <= this_dir;

                if (same_streak) begin
                    // Continuing streak: bump duty by the streak size
                    // already on record, then separately grow the streak
                    // (one op each, on different registers, not chained).
                    streak <= (streak == STREAK_MAX) ? STREAK_MAX : streak + 1'b1;
                    if (this_is_fast)      duty <= (duty <= step_amt)            ? '0       : duty - step_amt;
                    else if (this_is_slow) duty <= (duty >= DUTY_MAX - step_amt) ? DUTY_MAX : duty + step_amt;
                end else begin
                    // New streak starting (or holding): fixed 1-step bump,
                    // streak resets to 1 for a potential next occurrence.
                    streak <= {{(STREAK_BITS-1){1'b0}}, 1'b1};
                    if (this_is_fast)      duty <= (duty <= step_unit)            ? '0       : duty - step_unit;
                    else if (this_is_slow) duty <= (duty >= DUTY_MAX - step_unit) ? DUTY_MAX : duty + step_unit;
                end
            end
        end
    end

    // First-order delta-sigma DAC: `duty` is added into an accumulator
    // every clk_ref cycle, and the carry-out bit is the output bitstream.
    // Transitions can happen on any cycle (up to clk_ref/2 = 40MHz), and
    // the pattern is noise-shaped rather than a fixed low-frequency tone --
    // the average over any 2**DUTY_BITS-cycle window still equals
    // duty/2**DUTY_BITS exactly, but the ripple energy sits up near
    // Nyquist instead of concentrated at one low switching tone, which is
    // what actually lets the downstream analog filter shrink.
    reg [DUTY_BITS-1:0] sd_acc;
    reg                 dac_q;

    always @(posedge clk_ref or negedge rst_ni) begin
        if (!rst_ni) begin
            sd_acc <= '0;
            dac_q  <= 1'b0;
        end else begin
            {dac_q, sd_acc} <= sd_acc + duty;
        end
    end

    assign dac_out = dac_q;

endmodule

`default_nettype wire
